<?php

/**
 * Implements hook_field_extra_fields().
 */

function extra_fields_field_extra_fields() {
  $extra = array();
  foreach (node_type_get_types() as $type) {
    if ($type->has_title) {
      $extra['node'][$type->type]['display']['title'] = array(
        'label' => t('Extra field: !title', array('!title' => $type->title_label)),
        'weight' => -4,
        'type' => 'hidden',
      );
    }
    if($type->type == 'core_department'){
      $extra['node'][$type->type]['display']['core_link'] = array(
        'label' => t('Extra field: Core Dept Link'),
        'weight' => -4,
        'type' => 'hidden',
      ); 
    }
    if($type->type == 'person' || $type->type == 'research'){
      $extra['node'][$type->type]['display']['web_url'] = array(
        'label' => t('Extra field: Link to site'),
        'weight' => -4,
        'type' => 'hidden',
      ); 
    }
  }
 
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function extra_fields_node_view($node, $view_mode, $langcode) {
  // only return this in a non-full page situation
  if (!in_array($view_mode, array('default', 'full'))) {
    $node->content['title'] = array(
      '#theme' => 'extra_fields_title',
      '#node' => $node,
      '#view_mode' => $view_mode,
    ); 
  }
  if (in_array($view_mode, array('default', 'full'))) {
    $node->content['title'] = array(
      '#theme' => 'extra_fields_title_nolink',
      '#node' => $node,
      '#view_mode' => $view_mode,
    );  
  }
  $node->content['core_link'] = array(
      '#theme' => 'extra_fields_core_link',
      '#node' => $node,
      '#view_mode' => $view_mode,
  ); 
  if($node->type == 'person' || $node->type == 'research'){
    $node->content['web_url'] = array(
        '#theme' => 'extra_fields_web_url',
        '#node' => $node,
        '#view_mode' => $view_mode,
    ); 
  }
}

/**
 * Implements hook_theme().
 */
function extra_fields_theme($existing, $type, $theme, $path) {
  return array(
    'extra_fields_title' => array(
      'variables' => array('node' => NULL, 'view_mode' => NULL),
    ),
    'extra_fields_title_nolink' => array(
      'variables' => array('node' => NULL, 'view_mode' => NULL),
    ),   
    'extra_fields_core_link' => array(
      'variables' => array('node' => NULL, 'view_mode' => NULL),
    ),   
    'extra_fields_web_url' => array(
      'variables' => array('node' => NULL, 'view_mode' => NULL),
    ),
  );
}

function theme_extra_fields_title($variables) {
  $node = $variables['node'];
  $view_mode = $variables['view_mode'];
  $entity_uri = entity_uri('node', $node);
  $link_title = l($node->title, $entity_uri['path']);
  
  if($node->type == 'core_department'){
      $link_title = t($node->title);
  }
  if($node->type == 'affiliated_units'){
      if(!empty($node->field_website_url)){
        $affiliate_url = $node->field_website_url[LANGUAGE_NONE][0]['url'];
        $link_title = l($node->title, $affiliate_url, array('attributes' => array('target'=>'_blank')));
      }else{
        $link_title = t($node->title); 
      }
  }
  
  $output = '<h2 class="node-title">';
  $output .= $link_title;
  $output .= '</h2>';
  return $output;
}

function theme_extra_fields_core_link($variables) {
  $node = $variables['node'];
  
  if(!empty($node->field_dept_website)){
      $url = $node->field_dept_website[LANGUAGE_NONE][0]['url'];
      $output = '<div class="core-dept-url">' . l('VISIT', $url, array('attributes' => array('target'=>'_blank'))) . ' Department website </div>';
      return $output;
  }
}
function theme_extra_fields_web_url($variables) {
  $node = $variables['node'];

  if($node->type == 'person' && !empty($node->field_website_url)){
      $url = $node->field_website_url[LANGUAGE_NONE][0]['url'];
      
      $fname = $node->field_first_name[LANGUAGE_NONE][0]['value'];
      $mname = '';
      if(!empty($node->field_middle_name)){
        $mname = ' ' . $node->field_middle_name[LANGUAGE_NONE][0]['value'];
      }
      $lname = ' ' . $node->field_last_name[LANGUAGE_NONE][0]['value'];
      
      $link_text = 'More about ' . $fname . $mname . $lname;
      
      $output = '<div class="person-web-url">' . l($link_text, $url, array('attributes' => array('target'=>'_blank'))) . '</div>';
      
      return $output;
  }
  if($node->type == 'research' && !empty($node->field_website_url)){
      $url = $node->field_website_url[LANGUAGE_NONE][0]['url'];
          
      $output = '<div class="research-web-url">' . l('VISIT', $url, array('attributes' => array('target'=>'_blank'))) . ' project website</div>';
      
      return $output;
  }
}

function theme_extra_fields_title_nolink($variables) {
  $node = $variables['node'];
  $output = '<h2 class="node-title">';
  $output .= $node->title;
  $output .= '</h2>';
  return $output;
}

/* Features implementation for exporting extra fields information */

/**
 * Implements hook_features_api.
 */
function extra_fields_features_api() {
  return array(
    'extra_fields' => array(
      'name' => t('Extra fields'),
      'default_hook' => 'extra_fields_info',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'features_source' => TRUE,
      'file' => drupal_get_path('module', 'extra_fields') .'/extra_fields.features.inc',
    ),
  );
}